---
- name: copy the platform file from controller to target
  copy:
    src: "{{ patch_source_directory }}{{ platform_patchId }}.L7P"
    dest: "{{ patch_target_directory }}{{ platform_patchId }}.L7P"
    owner: ssgconfig
    group: ssgconfig
    mode: 755
- name: copy the application file from controller to target
  copy:
    src: "{{ patch_source_directory }}{{ application_patchId }}.L7P"
    dest: "{{ patch_target_directory }}{{ application_patchId }}.L7P"
    owner: ssgconfig
    group: ssgconfig
    mode: 755
