---
# This task reboots and waits for connection availability
- name: Unconditionally reboot the machine with all defaults
  reboot:

- name: Wait 300 seconds, but only start checking after 60 seconds
  wait_for_connection:
    delay: 60
    timeout: 300
